export const armorsList = [
  {
    index: 1,
    imgSrc: "/images/armors/html.png",
    title: "HTML",
    content: "1.5+ years of experience.",
    width: 2000,
    height: 2000,
  },
  {
    index: 2,
    imgSrc: "/images/armors/css.png",
    title: "CSS",
    content: "1.5+ years of experience.",
    width: 2000,
    height: 2000,
  },
  {
    index: 3,
    imgSrc: "/images/armors/sass.png",
    title: "SCSS",
    content: "1.5+ years of experience.",
    width: 2000,
    height: 2000,
  },
  {
    index: 4,
    imgSrc: "/images/armors/vanillajs.png",
    title: "Vanilla JS",
    content: "1+ years of experience.",
    width: 2000,
    height: 2000,
  },
  {
    index: 5,
    imgSrc: "/images/armors/reactjs.png",
    title: "React JS",
    content: "1+ years of experience.",
    width: 2000,
    height: 2000,
  },
  {
    index: 6,
    imgSrc: "/images/armors/nextjs.png",
    title: "Next JS",
    content: "1+ years of experience.",
    width: 2000,
    height: 2000,
  },
  {
    index: 7,
    imgSrc: "/images/armors/tailwindcss.png",
    title: "Tailwind CSS",
    content: "1+ years of experience.",
    width: 2000,
    height: 2000,
  },
  {
    index: 8,
    imgSrc: "/images/armors/firebase.png",
    title: "Firebase",
    content: "1+ years of experience.",
    width: 2000,
    height: 2000,
  },
  {
    index: 9,
    imgSrc: "/images/armors/adobexd.png",
    title: "Adobe XD",
    content: "1+ years of experience.",
    width: 2000,
    height: 2000,
  },
  {
    index: 10,
    imgSrc: "/images/armors/figma.png",
    title: "Figma",
    content: "1+ years of experience.",
    width: 2000,
    height: 2000,
  },
];
